apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-lb
spec:
  selector:
    app: k8s-demo   # Match the labels of the pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  labels:
    app: k8s-demo
spec:
  replicas: 1 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: demo-app
        image: sampleimage 
      imagePullSecrets:
      - name: dockerreg
